### ISSUE TITLE
Great, but maybe consider using vite-electron-builder?

### ISSUE THREAD

**Issue by MentalGear** [ctwhome/top-sveltekit#1]
Thank you for this top codebase - just the techstack I normally use and wanted for electron.

However, electron is complex and tricky, especially security-wise. There's another great create-vite electron builder which is , front-end independent, well maintained, highly used and cleverly structured.

 `vite-electron-builder` however doesn't have a sveltekit renderer as of yet (only svelte).

Maybe you could consider providing your excellent sveltekit pack as a framework there,  instead of having the hassle of building and (more importantly) maintaining your own electron framework.

https://github.com/cawa-93/vite-electron-builder

**Comment by ctwhome** [comment]
This is amazing thanks for the feedback!

**Comment by MentalGear** [comment]
I was hoping I could use your sveltekit package by simply dropping it into the /renderer folder of "vite-electron-builder". Do you think this will work? :)

**Comment by ctwhome** [comment]
I have no idea, i never used it, let me know how it goes!

**Comment by MentalGear** [comment]
I'd be awesome if you could port you sveltekit package to `vite-electron-builder`.

**Comment by ctwhome** [comment]
I moved to tauri, so this repo will be focused on it.
